name: Pizza Carrello
favicon: null
layout_spectrum: 0.1667308525647968
typography_spectrum: 0.059719494078308344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5746563377324492
  lightness: 0.8837305356282741
  saturation: 0.7744210057426244
  rhythmicContrast: 0.9286679630167782
purpose: []
